export const generalPracticeOptions: string[] = [
  "Small animal",
  "Large animal",
  "Equine",
  "Mixed animal",
  "Dairy",
  "Exotics",
  "Research",
  "Industry",
  "Government",
  "Other",
];

export const specialistOptions: string[] = [
  "Anesthesia and Analgesia",
  "Behavior",
  "Dentistry",
  "Dermatology",
  "Emergency and Critical Care",
  "Internal Medicine, small animal",
  "Internal Medicine, large animal",
  "Laboratory Animal Medicine",
  "Microbiology",
  "Nutrition",
  "Oncology",
  "Ophthalmology",
  "Pathology",
  "Pharmacology",
  "Preventive Medicine",
  "Radiology",
  "Sports Medicine and Rehabilitation",
  "Surgery, small animal",
  "Surgery, large animal",
  "Theriogenology",
  "Toxicology",
  "Veterinary Practitioners",
  "Zoological Medicine",
];

export const paymentFrequencyOptions: string[] = ["Annually", "Hourly"];
